name: yatt
title: yatt | Las cosas que venías buscando
description: yatt te trae las cosas útiles e interesantes del internet.
  ¡Siempre contenidos de alta calidad y actualizados!
tags:
  - blog
  - template
  - jekyll
  - theme
show_hero: false
paginate: 17
menu:
  - title: Inicio
    url: /
  - title: Acerca de
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
